### PR TITLE
using xxd files

### PR DESCRIPTION
**Pull request by scarrazza**
Implements the suggestion from #4. @AleCandido I have tested and predictions are unchanged.

### CODE REVIEW

**Review by alecandido — APPROVED** [review]
Looks good to me!

@niclaurenti can you try:
- running the usual photon computation installing from source
- build the conda package on one computer (even your laptop) and install with that one on another one?

**Comment by scarrazza** [comment]
@AleCandido if you prefer I can go ahead and produce the pip/conda release. 
I am not particularly worried about having to release further fixes.

**Comment by alecandido** [comment]
> @AleCandido if you prefer I can go ahead and produce the pip/conda release.

That's also an option. If everything is straightforward for the conda release, please keep going

**Comment by scarrazza** [comment]
Yes, let's try.

**Comment by niclaurenti** [comment]
> Looks good to me!
> 
> @niclaurenti can you try:
> 
> * running the usual photon computation installing from source
> * build the conda package on one computer (even your laptop) and install with that one on another one?

Both points worked fine

**Pull request merged**
