### PR TITLE
Building wheels

### PR DESCRIPTION
**Pull request by scarrazza**

### CODE REVIEW

**Comment by alecandido** [comment]
I saw the wheels, so you did it!

`musllinux` is nice to have, but I don't believe is our main concern (for as long as the fit won't run in a micro contrainer), and also PyPy is nice, but I have no experience of anyone using (we might even lack dependencies from someone else). In any case, if you are able to, it doesn't hurt :)
(same for Python 3.6, I don't believe any major distro still uses it, since it's end of life https://devguide.python.org/versions/)

**Comment by scarrazza** [comment]
Yeah, in fact I did not managed yet to find the options to disable musllinux and old python!

**Comment by alecandido** [comment]
I saw you managed! No need for my help :)

**Comment by scarrazza** [comment]
If you now how a cleaner way to pickup the fortran compiler on Mac, I would appreciate. I think they called it gfortran-11, so this means that we need to export FC=gfortran-11 only for mac builds...

**Comment by alecandido** [comment]
> If you now how a cleaner way to pickup the fortran compiler on Mac, I would appreciate. I think they called it gfortran-11, so this means that we need to export FC=gfortran-11 only for mac builds...

I can look for, but the basic answer is just "no". Do I look like a Mac user? :upside_down_face:

P.S.: however, my best guess is that CMake might be able to do it for you (metabuild systems are there for portability in the first place)

**Comment by alecandido** [comment]
> P.S.: however, my best guess is that CMake might be able to do it for you (metabuild systems are there for portability in the first place)

Ok, no this was stupid: you are not using CMake to build the wheel. Then, I'll look for cibuildwheel and friends...

**Comment by scarrazza** [comment]
Ok, this last commit worked... Let me try windows again so tomorrow I can make a release and propose the conda recipe.

**Comment by alecandido** [comment]
In case you will need to drop the action later on, its code is extremely simple:
https://github.com/modflowpy/install-gfortran-action/blob/d1979765a1a46c10711ce70197feb669085e1fd7/action.yml#L6-L34

The same thing can also be done by `cibuildwheel` env vars (but it seems easier to me to do it in the workflow, with the workflow's `if`s, rather than using `cibuildwheel` env vars).
https://cibuildwheel.readthedocs.io/en/stable/options/#before-all

**Comment by alecandido** [comment]
No one of us is really using Windows...
It is disappointing not to be able to release for all the options, but there is really no use case for the time being.

**Comment by scarrazza** [comment]
Yeah, we will probably have better luck with conda...

**Comment by alecandido** [comment]
In principle, [this guy](https://github.com/Nicholaswogan/NumbaMinpack) has been able to sort it out, but it was one year ago...

His workflow is extremely simple:
https://github.com/Nicholaswogan/NumbaMinpack/blob/ba54029a1bb41f315b76eed557d4e7582830142e/.github/workflows/build_wheels.yml
so I don't know why he was able to compile on Windows, and here has not been possible.

EDIT: found from this comment https://github.com/pypa/cibuildwheel/discussions/764#discussioncomment-1720251

**Comment by scarrazza** [comment]
Given that https://github.com/scarrazza/fiatlux/actions/runs/3339626885 works, I will remove windows and merge.

**Comment by alecandido** [comment]
Before merging, just remember re-enable the uploading of wheels. In any case, with current code, it would only happen on official releases:
https://github.com/scarrazza/fiatlux/blob/2ddd1cc3ab4885ddb1ce6e25e39421fcf2dfb2e5/.github/workflows/pip.yml#L75
(thus excluding both bare tags and pre-releases, even too strict for me)

**Comment by alecandido** [comment]
Moreover, in case you don't want (or don't need) to have artifacts separately downloadable, you could also use [job outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs).

But it is already working, so I would first merge, and if relevant reconsider this later on (or just forget).

EDIT: just forget, it is severely limited
> Outputs are Unicode strings, and can be a maximum of 1 MB. The total of all outputs in a workflow run can be a maximum of 50 MB.

**Comment by scarrazza** [comment]
I will uncomment after a first manual release, so it is easier to get the token.

**Pull request merged**
